### PR TITLE
Support tenable API keys

### PR DESCRIPTION
**Pull request by pemontto**
This PR includes support for using tenable.io API keys over the deprecated session endpoint.

### CODE REVIEW

**Comment by pemontto** [comment]
Need to get this working with Nessus also

**Comment by pemontto** [comment]
closes #96

**Comment by pemontto** [comment]
Travis build needs to be kicked of again, there was a 500 error bringing up the docker environment

**Comment by reactor7171** [comment]
Tested and working like charm, thanks @pemontto!

**Pull request merged**
