### PR TITLE
Docker-compose fully working with vulnwhisperer integrated

### PR DESCRIPTION
**Pull request by reactor7171**
- Added again fix for ignore requests warnings on nessus calls
- Modified docker-compose in order to include vulnwhisperer project, and make it work all together with the ELK stack out of the box, making it easily available for everyone. Added very specified instructions in case of users having issues with the deployment.
It uses a local folder to store the vulnwhisperer data, making it persistent even though the docker-compose gets killed; Logstash will process from that local folder with the scan info.

Changed:
- hostnames from docker-compose as there are configuration issues with ELK when hostnames have underscore and breaks them.
- added docker specified copies from logstash config files to make docker-compose work out of the box
- changed the paths at frameworks_example.ini from /opt/vulnwhisperer  to /opt/VulnWhisperer/data/ adapting to the already existent VulnWhisperer Dockerfile (https://github.com/HASecuritySolutions/docker_vulnwhisperer)

Will need to create a version/tag of vulnwhisperer when possible in order to change the Dockerfile of vulnwhisperer and make it stable, in order to solve the second bullet point at https://github.com/qmontal/VulnWhisperer#docker-compose.

### CODE REVIEW

**Comment by reactor7171** [comment]
This will solve issues #85 and #19, #13 should be also resolved in combination of this with PR #88.

**Comment by reactor7171** [comment]
@austin-taylor just noticed that the nessus warnings suppress was already changed by you (my change was here https://github.com/austin-taylor/VulnWhisperer/pull/90/commits/5e15321d551cb869bc20074bbfd9d005c47f3082), maybe you can delete that change and merge the rest :)

**Comment by austin-taylor** [comment]
@qmontal - This is awesome!! Do you have any screenshots for detectify? Great additions!!

**Comment by reactor7171** [comment]
Hi @austin-taylor, 

I will be working now on the Detectify integration; I was starting the integration from the frameworks-example.ini file -> vuln_vulnwhisperer -> vulnwhisp -> framework, and as I was already changing the frameworks-example.ini file, I did benefit of the commit to add the extra lines.

If you find it appropriate, those files can be ignored from the file while the Detectify integration is not ready.

**Comment by reactor7171** [comment]
Hi @austin-taylor ,

Don't merge yet the code, I encountered an error from docker when parsing the Qualys Vuln Management credentials in the qualysapi side (the error just pops on the docker part, the normal vulnwhisperer works as expected).

`QualysGuard Username: [ERROR] Could not connect to Qualys - EOF when reading a line`

Seems like for some reason, on Docker, qualysapi turns into interactive mode for authentication, although it still breaks after authenticating.

```
QualysGuard Username: ^CTraceback (most recent call last):
  File "/usr/bin/vuln_whisperer", line 5, in <module>
    pkg_resources.run_script('VulnWhisperer==1.5.0', 'vuln_whisperer')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/VulnWhisperer-1.5.0-py2.7.egg/EGG-INFO/scripts/vuln_whisperer", line 71, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/VulnWhisperer-1.5.0-py2.7.egg/EGG-INFO/scripts/vuln_whisperer", line 51, in main
    vw.whisper_vulnerabilities()
  File "/usr/lib/python2.7/site-packages/VulnWhisperer-1.5.0-py2.7.egg/vulnwhisp/vulnwhisp.py", line 921, in whisper_vulnerabilities
    vw = vulnWhispererQualysVuln(config=self.config)
  File "/usr/lib/python2.7/site-packages/VulnWhisperer-1.5.0-py2.7.egg/vulnwhisp/vulnwhisp.py", line 778, in __init__
    self.qualys_scan = qualysVulnScan(config=config)
  File "/usr/lib/python2.7/site-packages/VulnWhisperer-1.5.0-py2.7.egg/vulnwhisp/frameworks/qualys_vuln.py", line 92, in __init__
    self.qw = qualysWhisperAPI(config=config)
  File "/usr/lib/python2.7/site-packages/VulnWhisperer-1.5.0-py2.7.egg/vulnwhisp/frameworks/qualys_vuln.py", line 20, in __init__
    self.qgc = qualysapi.connect(config)
  File "/usr/lib/python2.7/site-packages/qualysapi/util.py", line 22, in connect
    remember_me_always=remember_me_always)
  File "/usr/lib/python2.7/site-packages/qualysapi/config.py", line 156, in __init__
    username = raw_input('QualysGuard Username: ')
```

**Comment by austin-taylor** [comment]
Thanks for testing @qmontal - will wait until you approve

**Comment by reactor7171** [comment]
Hi @austin-taylor,

Qualys modules are working now, the issue was that the Dockerfile used did not have updated the qualysapi dependencies, thus breaking the code.

I added a link on the README.md to the working [Dockerfile](https://raw.githubusercontent.com/qmontal/docker_vulnwhisperer/master/Dockerfile) on my repo; I will wait for you to create the new version tag of vulnwhisperer before making the PR to the original repo, as we need to specify the version of VulnWhisperer in order to make the container stable, and the latest version doesn't have the latest updates to make it all work together.

Once we have the tag and the changes merged with the Docker repo, we will need @SMAPPER to update the file in Docker Hub in order to make the docker-compose file working directly without extra steps.

Cheers!

**Comment by reactor7171** [comment]
Hi @austin-taylor,

I have noticed that something that seemed to be working is actually broken, on the logstash configuration part. I will fix it and do another PR as soon as I have it working properly.

Do you want me to set up the vulnwhisperer slack channel in order to talk about the project without filling Github of comments? :)

**Comment by austin-taylor** [comment]
@qmontal - I've created a slack channel: https://join.slack.com/t/vulnwhisperer/shared_invite/enQtNDIwMTM5Njk4Nzc1LTM2Y2UyMmQ3MDhmYmQ1ODgyMjI5MWRjMmFlNjg4N2M2ZDY3MzI3NGVjZTU4YTNjYmIwNzRlMjdhMTVhMTUyMDA

**Pull request merged**
