### PR TITLE
V6 Dashboard

### PR DESCRIPTION
**Pull request by cybergoof**
Kibana visualizations files for ELK stack 6.5.   They should be imported into Kibana just like the current version.

I do not have a test environment to properly test the import/export a few times.  So let me know if there are problems.

### CODE REVIEW

**Comment by austin-taylor** [comment]
Have any sanitized screenshots by chance @cybergoof ?

**Comment by cybergoof** [comment]
No screenshots, I just don't have any test data.  But the screens didn't' change.  There were just a few terms that had changed. 

I did remove all the orphaned visualizations.

**Comment by cybergoof** [comment]
I looked at the travis error.  That doesn't look like something I did?

**Comment by cybergoof** [comment]
I did a few things.  i created a unique count of a new, scripted value.  This is stopping the double counting.  It might be slower, but I don't have enough metrics.   it does allow us to get unique plugin findings per asset without doublecounting when running a scan twice.

I also have all the dashboards, visualizations, etc into one file.  I can parse them out if that is more acceptable.  But seems Kibana 6 isn't that picky anymore.

**Pull request merged**
