### PR TITLE
Rework logging using the stdlib machinery

### PR DESCRIPTION
**Pull request by uovobw**
It's a dirty job but someone must do it.

This patch reworks logging method for the whole project, it uses the standard python stdlib logging machinery (that can be configured in the main binary during startup) and avoids the use of home-made `vprint` functions and so on. It also removes the use of bcolors, that are bad in exceptions and can make the log output complex to parse/handle for external tools.

This is a work in progress, ideally i'd like to test and iterate with @qmontal until we reach a satisfactory situation.

### CODE REVIEW

**Comment by uovobw** [comment]
@qmontal i cannot add you as reviewer for this PR, not sure if it's due to my collaborator settings. let me know, thanks

**Comment by reactor7171** [comment]
@uovobw do you think we could keep the coloring, as it is much easier for the users to follow the process that is taking place during the execution of VulnWhisperer and highlights the status of the different steps that are being processed?
I think this is an important feature for those who want to use VulnWhisperer as their aggregation tool, without needing extra effort of understanding the inner workings of the tool or have to pay too much attention to the verbose, it looks pretty clean and clear the output and status.

**Comment by uovobw** [comment]
ok, waiting on approval. if we get it, i'll integrate the coloration code in the main executable and re-push on this branch. thanks for the review.

**Comment by uovobw** [comment]
`coloredlogs` added to requirements and `--fancy` flag added to the main executable

**Comment by austin-taylor** [comment]
Approved. Thank you for your contribution @uovobw!

**Comment by reactor7171** [comment]
#78 considered done.

**Pull request merged**
