### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rogierm**
Update README to include instruction to increase vm.max_map_count

### CODE REVIEW

**Comment by reactor7171** [comment]
Hi @rogierm,
The instruction you mentioned is actually commented on the 5th bullet of the docker-compose instructions, maybe we should change that to make it more clear? 
Cheers

Edit: also the reason to put the link instead of the command was to have easy access to the Windows solution as well :)

**Comment by austin-taylor** [comment]
We should create a wiki and build links in the README

**Comment by reactor7171** [comment]
Hi @austin-taylor,
That would be a good idea, although the only issue is that Wiki can't be contributed through PR, and I guess it would impact as well the current VulnWhisperer web page, as for now is being build from the README; definitely something to check :) 
BR

**Comment by rogierm** [comment]
Hi Quim, the page looks very clear to me now! I'm sure I wouldn't miss it again :). Thanks!

**Comment by reactor7171** [comment]
Thank you! :)

**Pull request closed without merging**
