### PR TITLE
Tenable.io support

### PR DESCRIPTION
**Pull request by pemontto**
This commit adds basic Tenable.io support leveraging most of the existing Nessus class.

In its current form it doesn't support folders.

This is also using the username and password to generate a session token which is deprecated. Needs some more work to use API keys for tenable.io.

### CODE REVIEW

**Review by austin-taylor — COMMENTED** [review]
Awesome! Do you have any screenshots you can share? Looking for data schema and a populated dashboard if possible

**Comment by pemontto** [comment]
Ahh I missed the Logstash config, I've been using my own fork that exports the Nessus DataFrame as JSON.

The additional fields produced by the Tenable export are:
`System Type,MAC Address,Host Start,FQDN,IP Address,Host End,Plugin Family,Asset UUID,OS,Vulnerability State,NetBios`

**Comment by pemontto** [comment]
Updated the Logstash config. Tested on both Nessus and Tenable exports.

tenable-dashboard256

Kibana JSON of one of the tenable documents:
```json
{
  "_index": "logstash-vulnwhisperer-tenable",
  "_type": "doc",
  "_id": "lg9LAWQBJ14ml4nyO7QJ",
  "_version": 1,
  "_score": null,
  "_source": {
    "plugin_family": "Misc.",
    "risk": "Medium",
    "description": "The remote Extensible Messaging and Presence Protocol (XMPP) service\nsupports one or more authentication mechanisms that allow credentials\nto be sent in the clear.",
    "@timestamp": "2018-05-04T16:59:30.000Z",
    "system_type": "general-purpose",
    "cvss": "4.3",
    "cvss_base": "4.3",
    "@version": "1",
    "port": "5222",
    "plugin_name": "XMPP Cleartext Authentication",
    "path": "/opt/vulnwhisperer/tenable/TestScan_20_10481880_1525453170.csv",
    "solution": "Disable cleartext authentication mechanisms in the XMPP configuration.",
    "risk_score_name": "medium",
    "vulnerability_state": "Active",
    "scan_name": "TestScan",
    "plugin_id": "87736",
    "host_end": "2018-05-04T01:57:36.325Z",
    "fqdn": "xmpp.example.com",
    "asset_uuid": "17f1e5f8-6dfa-48da-bc4e-8f98a99cd3e2",
    "host": "log.example.com",
    "host_start": "2018-05-04T01:14:35.933Z",
    "risk_score": 4.3,
    "operating_system": "Linux Kernel 3.10 on CentOS Linux release 7",
    "history_id": "10481880",
    "risk_number": "2",
    "tags": [
      "tenable"
    ],
    "ip": "1.1.1.1",
    "synopsis": "The remote host is running a service that allows cleartext\nauthentication.",
    "scan_id": "20",
    "protocol": "TCP",
    "type": "tenable",
    "asset": "1.1.1.1"
  }
}
```

**Review by austin-taylor — APPROVED** [review]

**Comment by austin-taylor** [comment]
What's left for full integration here? Database tracking?

**Comment by pemontto** [comment]
That's already working

```
sqlite> .header on
sqlite> .mode column
sqlite> select * from scan_history;
id          scan_name                   scan_id     last_modified  filename                                               download_time     record_count  source      uuid                                  processed 
----------  --------------------------  ----------  -------------  -----------------------------------------------------  ----------------  ------------  ----------  ------------------------------------  ----------
1           alice with FW               50          1529081834     alice_with_FW_50_10024925_1529081834.csv               1529028599.85272  15            tenable     72a45402-1826-45b4-b08c-2be6ac04214e  1         
2           alice with FW               50          1529080933     alice_with_FW_50_10024921_1529080933.csv               1529028600.93243  4             tenable     bc11b45d-cbe8-4afc-afb6-9bf0eee5930f  1         
4           Basic Scan                  44          1528408485     Basic_Scan_44_10022316_1528408485.csv                  1529028610.27326  32            tenable     5e046fbc-852f-4ac2-9ea6-aaeaf74c2424  1         
5           ETest                       18          1525367244     ETest_18_10478657_1525367244.csv                       1529030007.98709  56            tenable     a5c2b890-5a86-4f4d-8442-5d650e27f48e  1         
6           Web Application Scan        31          1526339485     Web_Application_Scan_31_10521121_1526339485.csv        1529030015.66032  0             tenable     0ee4b5c7-671e-4702-8f6e-5996b284d2b9  1         
7           ExternalScan                20          1525486920     ExternalScan_20_10483537_1525486920.csv                1529030024.30242  48            tenable     2480fdab-d624-4e10-bf96-5725f766e317  1         
8           ExternalScan                20          1525453170     ExternalScan_20_10481880_1525453170.csv                1529030032.21716  66            tenable     a78fba0d-3a9e-44e7-a168-71fe61879dc6  1         
9           Public IP Basic Scan        29          1526338465     Public_IP_Basic_Scan_29_10520965_1526338465.csv        1529030039.34803  10            tenable     871fc71f-e6a8-47e4-bbcf-3716bee24163  1         
```

**Review by austin-taylor — APPROVED** [review]

**Comment by austin-taylor** [comment]
Excellent contribution. Thank you! Do you have a twitter handle?

**Pull request merged**
